name = "Microstructure"
uuid = "bb9cb41e-5262-42dc-ac73-4f266bc6ab72"
authors = ["Ting Gong"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
